# DataSource Config
server:
    port: 8089
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        #schema: classpath:db/schema-h2.sql
        #data: classpath:db/data-h2.sql
        url: jdbc:mysql://localhost:3306/world?useUnicode=true&useSSL=true&serverTimezone=UTC
        username: root
        password: root

# Logger Config
logging:
    level:
      com.neo: debug
